server:
  port: 9092
  servlet:
    context-path: /bs-sales

spring:
  application:
    name:app-sales-room
  datasource:
    url: jdbc:mysql://localhost:3306/sales_room
    username: lab01user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs
  swagger-ui.tagsSorter: alpha
  swagger-ui.operationsSorter: alpha

